# version: '3.8'
# services:
#   frontend:
#     build: 
#       context: .
#     command: npm run dev
#     ports: 
#       - '3000:3000'
#     volumes:
#       - ./:/frontend
#       - /frontend/node_modules
  
#   nginx:
#     build:
#       context: ./nginx
#     restart: always
#     ports:
#       - "3000:80"
#     volumes:
#       - ./:/usr/share/nginx/html
#     links:
#       - "frontend"

version: '3'
services:
  nextjs:
    build: ./
  # nginx:
  #   build: ./nginx
  #   ports:
  #     # - 80:80
  #     - 3000:3000
     
      
